name: Make Nagoya PMTiles

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '21'

      - name: Download Planetiler
        run: |
          wget https://github.com/onthegomap/planetiler/releases/download/v0.10.2/planetiler.jar

      - name: Convert OSM XML to PBF
        run: |
          java -Xmx4g -jar planetiler.jar \
            --osm_path=osm.xml \
            --output=osm.pbf \
            --download

      - name: Check OSM XML
        run: |
          ls -lh osm.xml
          file osm.xml
          head -n 10 osm.xml

      - name: Generate PMTiles
        run: |
          java -Xmx4g -jar planetiler.jar \
            --osm_path=osm.pbf \
            --output=map.pmtiles \
            --download

      - name: Upload PMTiles
        uses: actions/upload-artifact@v4
        with:
          name: nagoya-map
          path: map.pmtiles